### PR TITLE
Fix:Invalid values are accepted for the date of birth of a customer

### PR DESCRIPTION
**Pull request by jb1998**
screenshot_2018-01-14-09-07-00

Fixes {#175}

- [ ] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [ ] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [ ] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by therajanmaurya** [comment]
@jb1998 As I am seeing, It's already fixed. @jb1998 Please comment on issue before working on any issue so that others can know you are working on otherwise This thing can happen again like you did not comment and somebody was already working and He commented and His solution was good.

So Please before picking any issue just comment and look others not working on.

**Comment by jb1998** [comment]
I am sorry for that.
Actually I used to make my projects open source and I just started with contributing to other open source projects , I saw the issue open so I started working on it.
From now onwards I will first ask in comments.
Thanks for guiding me :)

**Comment by therajanmaurya** [comment]
@jb1998 Great, If you are picking an issue and no commented before then you pick the issue by commenting `I am working in this issue` If you are the first person who is commenting on the issue.

**Comment by jb1998** [comment]
Okay I will follow that :)

**Pull request closed without merging**
