### PR TITLE
Fix: Ok/Cancel buttons visible in DatePicker

### LINKED ISSUE #174: No Ok/Cancel buttons in DatePicker for Date of birth
**Summary:** 

Ok and Cancel buttons not visible in Datepicker dialog in Customer Details form

**Steps to reproduce:** 

View Customer -> Click on any customer -> Edit-> Click on Date of birth

**Expected behavior:** 

Ok and Cancel buttons should be visible

**Device and Android version:** 

OnePlus 5, Android 7.1.1

**Screenshots:** 

screenshot_20180109-230954

**Would you like to work on this?**

Yes

### PR DESCRIPTION
**Pull request by nb2998**
Fixes #174 

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by nb2998** [comment]
@therajanmaurya Kindly review.
Doing this, text color of all buttons except the 2 on dashboard has been changed to accent color. Please let me know if some other approach has to be followed.
Thanks.

**Comment by therajanmaurya** [comment]
This is not good solution, Please see this https://github.com/openMF/mifos-mobile/pull/402

**Comment by therajanmaurya** [comment]
Project style should always be independent of others.

**Comment by nb2998** [comment]
@therajanmaurya Please help me to understand why is the travis build failing. The unit tests ran successfully.

**Comment by therajanmaurya** [comment]
@nb2998 It's because your check style not passing. Please see this https://travis-ci.org/openMF/Fineract-CN-mobile/builds/328233458#L2240 and give a white space and all will be good. 

Before pushing code please follow the second step of PR description.

**Comment by nb2998** [comment]
The issue was with the maximum number of allowed characters on a single line. I solved it and the build was successful after that on running `./gradlew check`. But the travis is still failing with no log available.

**Comment by therajanmaurya** [comment]
Good work @nb2998

**Pull request merged**
